parameters:
  - name: vmImage
    displayName: 'Pool VM image'
    type: string
    default: 'ubuntu-latest'
    values:
      - windows-latest
      - ubuntu-latest
      - macOS-latest

  - name: organization
    displayName: 'Azure DevOps organization'
    type: string
    default: 'godeltech'

  - name: project
    displayName: 'Azure DevOps project'
    type: string
    default: 'OpenSource'

  - name: repositoryFullName
    displayName: 'Repository full name'
    type: string
    default: 'GodelTech/azuredevops-pipelines'

  - name: repositoryType
    displayName: 'Repository type'
    type: string
    default: 'gitHub'

trigger:
  batch: true
  paths:
    include:
      - .azuredevops/CI.yml
      - '.scripts/*'
      - '**/*.yml'
      - '*'
    exclude:
      - README.md
      - LICENSE

pr:
  branches:
    include:
      - '*'

schedules:
  - cron: '0 0 1 * *'
    displayName: 'Monthly check'
    branches:
      include:
        - main
    always: true

jobs:
  - job: Lint
    displayName: 'YAML lint'
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        displayName: 'Use Python 3.x'
        inputs:
          versionSpec: '3.x'

      - script: pip install yamllint
        displayName: 'Install yamllint'

      - script: yamllint .
        displayName: 'Run yamllint'

  - job: CheckPrettier
    displayName: 'Check prettier'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: Lint
    variables:
      npm_config_cache: $(Pipeline.Workspace)/.npm
    steps:
      - checkout: self

      - task: NodeTool@0
        displayName: 'Use Node.js'
        inputs:
          versionSpec: '22.x'

      - task: Cache@2
        displayName: 'Cache npm packages'
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
            npm
          path: $(npm_config_cache)

      - script: npm install
        displayName: 'npm install'

      - script: npx prettier . --check
        displayName: 'Run prettier'

  - job: CheckTemplateReferences
    displayName: 'Check template references'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckPrettier
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-template-references'
        inputs:
          filePath: '.scripts/check-template-references.ps1'
          pwsh: true

  - job: CheckTriggers
    displayName: 'Check triggers'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckTemplateReferences
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-triggers'
        inputs:
          filePath: '.scripts/check-triggers.ps1'
          pwsh: true

  - job: CheckPR
    displayName: 'Check PR'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckTriggers
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-pr'
        inputs:
          filePath: '.scripts/check-pr.ps1'
          pwsh: true

  - job: CheckSchedules
    displayName: 'Check schedules'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckPR
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-schedules'
        inputs:
          filePath: '.scripts/check-schedules.ps1'
          pwsh: true

  - job: CheckCancelBuild
    displayName: 'Check cancel build'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckSchedules
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-cancel-build'
        inputs:
          filePath: '.scripts/check-cancel-build.ps1'
          pwsh: true

  - job: CheckBuildSummaryValidation
    displayName: 'Check build summary validation'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckCancelBuild
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-build-summary-validation'
        inputs:
          filePath: '.scripts/check-build-summary-validation.ps1'
          pwsh: true

  - job: CheckTestCoverage
    displayName: 'Check test coverage'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckBuildSummaryValidation
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-test-coverage'
        inputs:
          filePath: '.scripts/check-test-coverage.ps1'
          pwsh: true

  - job: CheckPipelines
    displayName: 'Check pipelines'
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn: CheckTestCoverage
    steps:
      - checkout: self

      - task: PowerShell@2
        displayName: 'Run check-pipelines'
        inputs:
          filePath: '.scripts/check-pipelines.ps1'
          arguments: >-
            -Organization '${{ parameters.organization }}'
            -Project '${{ parameters.project }}'
            -AccessToken $(System.AccessToken)
            -RepositoryFullName '${{ parameters.repositoryFullName }}'
            -RepositoryType '${{ parameters.repositoryType }}'
          pwsh: true
