parameters:
  - name: enableBuildDebug
    displayName: 'Enable build debug'
    type: boolean
    default: false

  - name: projects
    displayName: 'Projects to build'
    type: string
    default: ''

  - name: configuration
    displayName: 'Build configuration'
    type: string
    default: 'Release'

  - name: verbosity
    displayName: 'MSBuild verbosity level'
    type: string
    default: 'minimal'
    values:
      - quiet
      - minimal
      - normal
      - detailed
      - diagnostic

  - name: noRestore
    displayName: 'Do not restore packages before building'
    type: boolean
    default: true

  - name: selfContained
    displayName: 'Publish the .NET runtime with the application'
    type: boolean
    default: false

  - name: workingDirectory
    displayName: 'Working directory'
    type: string
    default: ''

steps:
  - pwsh: |
      $args = "--configuration ${{ parameters.configuration }}"
      $args += " --verbosity ${{ parameters.verbosity }}"
      if ([System.Convert]::ToBoolean($env:NO_RESTORE)) { $args += " --no-restore" }
      if ([System.Convert]::ToBoolean($env:SELF_CONTAINED)) { $args += " --self-contained" }
      Write-Host "##vso[task.setvariable variable=dotnetBuildArguments]$args"
    displayName: 'Set dotnet build arguments'
    env:
      NO_RESTORE: ${{ parameters.noRestore }}
      SELF_CONTAINED: ${{ parameters.selfContained }}

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      ${{ if ne(parameters.projects, '') }}:
        projects: ${{ parameters.projects }}
      arguments: $(dotnetBuildArguments)
      ${{ if ne(parameters.workingDirectory, '') }}:
        workingDirectory: ${{ parameters.workingDirectory }}
